
base:
  path: ""

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.aiqingjun: debug
    org.springframework: warn

#Shiro
shiro:
  user:
    #登录地址
    loginUrl: ${base.path}/login
    #权限认证失败地址
    unauthorizedUrl: ${base.path}/unauth
    #首页地址
    indexUrl: ${base.path}/index
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # session有效性检测的间隔时间（默认10分钟）
    validationInterval: 10

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/sys?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.aiqingjun.model
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
